﻿// This file was auto-generated by ML.NET Model Builder. 
using System.Linq;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML;

namespace Application
{
    public partial class NewsModel
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(@"id", @"id")      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"title", @"title"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"author", @"author"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"text", @"text"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"id",@"title",@"author",@"text"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(@"label", @"label"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.OneVersusAll(binaryEstimator:mlContext.BinaryClassification.Trainers.FastForest(new FastForestBinaryTrainer.Options(){NumberOfTrees=4,FeatureFraction=1F,LabelColumnName=@"label",FeatureColumnName=@"Features"}), labelColumnName: @"label"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(@"PredictedLabel", @"PredictedLabel"));

            return pipeline;
        }
    }
}
